# Welcome to Jekyll!

# Website settings
baseurl: "/"
title: "段朝骞"
description: "zhaoqian's blog,use Jekyll and github pages."
keywords: "zhaoqian,duanzhaoqian,blog,段朝骞,github,gh-pages"

url: "duanzhaoqian.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: '段朝骞'
  first_name: 'zhaoqian'
  last_name: 'duan'
  email: 'duanzhaoqian@outlook.com'
  facebook_username: ''
  github_username: 'duanzhaoqian'
  head_img: 'static/img/landing/head.jpg'


# landing page
landing:
  home: 'Home'
  about: 'About'
  blog: 'Blog'
  link: 'Link'


# blog index
index:
  home: 'Home'
  java: 'Java'
  linux: 'Linux'
  html: 'HTML'
  database: 'Database'
  mac: 'Mac'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.jpg'
  alipay: 'static/img/pay/alipay.jpg'



# baidu analytics
ba:
  uuid: f259df62b106b184dcdef65ffedff7cf


# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
